spring:
  output:
    ansi:
      enabled: always
  application:
    name: payment
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/payment
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
      data-locations: classpath:db-init/test-data.sql

server:
  shutdown: graceful
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

logging:
  level:
    com.example: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"

payment:
  toss:
    key:
      client: access-key
      secret: secret-key # secret key ? base64? encoding ???

---

spring:
  config:
    activate:
      on-profile: test

  r2dbc:
    url: r2dbc:pool:h2://localhost/payment
  sql:
    init:
      mode: always